
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: dts
spec:
  replicas: 1
  selector:
    matchLabels: { app: scheduler }
  template:
    metadata:
      labels: { app: scheduler }
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/example/dts-scheduler:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SCHEDULER_DB_URL
              value: "jdbc:postgresql://postgres:5432/$(POSTGRES_DB)"
            - name: SCHEDULER_DB_USER
              valueFrom: { secretKeyRef: { name: dts-secrets, key: POSTGRES_USER } }
            - name: SCHEDULER_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: dts-secrets, key: POSTGRES_PASSWORD } }
            - name: SCHEDULER_BATCH_SIZE
              valueFrom: { configMapKeyRef: { name: dts-config, key: SCHEDULER_BATCH_SIZE } }
            - name: SCHEDULER_LOOP_DELAY_MS
              valueFrom: { configMapKeyRef: { name: dts-config, key: SCHEDULER_LOOP_DELAY_MS } }
