
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: dts
spec:
  replicas: 2
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: ghcr.io/example/dts-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ORCHESTRATOR_URL
              value: "http://orchestrator:8080"
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
